# Generated by Django 4.2 on 2023-07-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_usercashback_cashback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='orders',
        ),
        migrations.AddField(
            model_name='sale',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sale',
            name='gift_product',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
