# Generated by Django 4.2 on 2023-07-14 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_sale_orders_sale_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='gift_product',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='gift_quantity',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='required_quantity',
        ),
    ]
