# Generated by Django 4.2 on 2023-07-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_order_user_remove_orderdetail_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='for_gender',
            field=models.CharField(choices=[('👨\u200d💼 Erkaklar uchun', '👨\u200d💼 Erkaklar uchun'), ('👩\u200d💼 Ayollar uchun', '👩\u200d💼 Ayollar uchun')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='max_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='min_age',
            field=models.IntegerField(default=0),
        ),
    ]
