# Generated by Django 4.2 on 2023-07-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_news_for_gender_news_max_age_news_min_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='max_age',
            field=models.IntegerField(default=100),
        ),
    ]
