# Generated by Django 4.2 on 2023-07-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_news_max_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='for_gender',
            field=models.CharField(choices=[('👨\u200d💼 Erkaklar uchun', '👨\u200d💼 Erkaklar uchun'), ('👩\u200d💼 Ayollar uchun', '👩\u200d💼 Ayollar uchun'), ('Hamma uchun', 'Hamma uchun')], max_length=200, null=True),
        ),
    ]
