# Generated by Django 4.2 on 2023-10-08 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_news_image_remove_news_min_age_news_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image1',
            new_name='image',
        ),
    ]
