# Generated by Django 4.2 on 2023-10-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_rename_image1_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='min_age',
            field=models.IntegerField(default=0),
        ),
    ]
