# Generated by Django 4.2 on 2023-10-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_news_min_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.IntegerField(choices=[(0, 'Yaratildi'), (1, 'Bitirildi')], default=0),
        ),
    ]
