# Generated by Django 4.2 on 2023-10-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
