# Generated by Django 4.2 on 2023-10-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_notification_image2_notification_image3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Bildirishnoma', 'verbose_name_plural': 'Bildirishnomalar'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Aksiya', 'verbose_name_plural': 'Aksiyalar'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='edited_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='edited_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='edited_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
