# Generated by Django 4.2 on 2023-10-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_sale_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='description',
            field=models.TextField(verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='name',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Nomi'),
        ),
    ]
