# Generated by Django 4.2 on 2023-10-10 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_sale_description_alter_sale_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Yangilik ', 'verbose_name_plural': 'Yangiliklar '},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Bildirishnoma ', 'verbose_name_plural': 'Bildirishnomalar '},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Aksiya ', 'verbose_name_plural': 'Aksiyalar '},
        ),
        migrations.AlterField(
            model_name='news',
            name='for_gender',
            field=models.CharField(choices=[('👨\u200d💼 Erkaklar uchun', '👨\u200d💼 Erkaklar uchun'), ('👩\u200d💼 Ayollar uchun', '👩\u200d💼 Ayollar uchun'), ('Hamma uchun', 'Hamma uchun')], max_length=200, null=True, verbose_name='Kimlar uchun'),
        ),
        migrations.AlterField(
            model_name='news',
            name='max_age',
            field=models.IntegerField(default=100, verbose_name='Qaysi yoshgacha'),
        ),
        migrations.AlterField(
            model_name='news',
            name='min_age',
            field=models.IntegerField(default=0, verbose_name='Qaysi yoshdan'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='all_chats',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.IntegerField(choices=[(0, 'Yaratildi'), (1, 'Bitirildi')], default=0, editable=False),
        ),
        migrations.CreateModel(
            name='NewsShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news', verbose_name='Rasm')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.news')),
            ],
        ),
    ]
