# Generated by Django 4.2 on 2023-10-10 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_news_options_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsshots',
            options={'verbose_name': 'Yangilik rasmi ', 'verbose_name_plural': 'Yangilik rasmlari '},
        ),
        migrations.CreateModel(
            name='NotificationShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notification', verbose_name='Rasm')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.notification')),
            ],
            options={
                'verbose_name': 'Bildirishnoma rasmi ',
                'verbose_name_plural': 'Bildirishnoma rasmlari ',
            },
        ),
    ]
