# Generated by Django 4.2 on 2023-10-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_newsshots_options_notificationshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(blank=True, max_length=940, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='description',
            field=models.TextField(max_length=950, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='name',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Nomi'),
        ),
    ]
