# Generated by Django 4.2 on 2023-10-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_remove_sale_image_saleshots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='image',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='image5',
        ),
    ]
