# Generated by Django 4.2 on 2023-10-13 19:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_remove_news_image_remove_news_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=940, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=950, verbose_name='Izoh'),
        ),
    ]
