# Generated by Django 4.2 on 2023-10-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_news_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.IntegerField(choices=[(0, 'Yaratildi'), (1, 'Bitirildi'), (2, 'Jarayonda')], default=0, editable=False),
        ),
    ]
