# Generated by Django 4.2 on 2023-07-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=100)),
                ('moneyback_id', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=100)),
                ('otp', models.CharField(max_length=100)),
            ],
        ),
    ]
