# Generated by Django 4.2 on 2023-07-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_telegramuser_gender_alter_telegramuser_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='latitude',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='location',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='longitude',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
