# Generated by Django 4.2 on 2023-08-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_telegramchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchat',
            name='register_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='register_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
