# Generated by Django 4.2 on 2023-08-04 02:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_telegramchat_register_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchat',
            name='register_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='register_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
