# Generated by Django 4.2 on 2023-10-09 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0008_alter_telegramuser_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='register_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 10, 9), null=True),
        ),
    ]
