# Generated by Django 4.2 on 2023-10-12 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0010_alter_telegramuser_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='register_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 10, 12), null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
