# Generated by Django 4.2 on 2023-10-12 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0011_alter_telegramuser_register_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchat',
            name='register_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='register_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
