# Generated by Django 4.2 on 2023-10-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0012_alter_telegramchat_register_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchat',
            name='is_stopped',
            field=models.BooleanField(default=False),
        ),
    ]
